description = "Ubuntu bionic base image with buildpacks for Java, NodeJS and Golang"

[[order]]
group = [
  { id = "paketo-buildpacks/java-native-image" },
]

[[order]]
group = [
  { id = "paketo-buildpacks/java" },
]

[[order]]
group = [
  { id = "paketo-buildpacks/nodejs" },
]

[[order]]
group = [
  { id = "paketo-buildpacks/go" },
]

[[order]]
group = [
  { id = "paketo-buildpacks/dotnet-core" },
]

[[order]]
group = [
  { id = "paketo-buildpacks/nginx" },
]

[[order]]
group = [
  { id = "paketo-buildpacks/procfile" },
]
